finalproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from myapp.views import common,webuser,employer


urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', common.SignUpView.as_view(), name='signup'),
    path('accounts/signup/user/', webuser.WebUserSignUpView.as_view(), name='user_signup'),
    path('accounts/signup/employer/', employer.EmployerSignUpView.as_view(), name='employer_signup'),
   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.urls import path, include
from .views import common, webuser, employer

urlpatterns = [
    
    path('', common.home, name='home'),

    path('webuser/', include(([
        path('userhome', webuser.userhome, name="userhome"),   
        path('specificcompanypage/<str:company_name>', webuser.specificcompanypage, name="specificcompanypage"),   
      #  path('apply', webuser.media_upload, name='media_upload'),
        path('search', webuser.searchposts, name='searchposts'),
        path('sendmail', webuser.sendmail, name='sendmail'),
        path('giveratings', webuser.RatingsView.as_view(), name="Ratings"),
        path('viewratings/<str:company_name>', webuser.rate, name="rate"),
      path('companydetails', webuser.infopage, name='infopage'),
        path('pdfs/', webuser.downloadtemplate, name="downloadtemplate"), 

    ], 'classroom'), namespace='webuser')),
   
  
    


    path('employer/', include(([
        path('employerhome', employer.employerhome, name="employerhome"),      
        path('employerform', employer.EmployerFormView.as_view(), name="employerform"),
        path('ajax/filteravailableposts/', employer.filteravailableposts, name='ajaxfilteravailableposts'),
      # path('applications-received/<str:company_name>', employer.applications_received, name='applications_received'),
        path('filterapplications', employer.ApplicationsReceivedListView.as_view(), name="filterapplications"),
          path('specificcompanypage/<str:company_name>', employer.specific_companypage_employer, name="specific_companypage_employer"),
        path('update/<int:pk>/', employer.EmployerFormUpdateView.as_view(), name='update_form'),
        path('delete/<int:pk>/', employer.EmployerFormDeleteView.as_view(), name='delete_form'),
        path('mycompanyratings', employer.CompanyRatingsListView.as_view(), name="mycompanyratings"),
   




    ], 'classroom'), namespace='employer')),

]

myapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime  
from django.conf import settings
from django.forms.widgets import RadioSelect

class User(AbstractUser):
    is_webuser = models.BooleanField(default=False)
    is_employer = models.BooleanField(default=False)


class WebUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
        
    def __str__(self):
        return self.user.username


class CompanyType(models.Model):
    names = models.CharField(max_length=200)

    def __str__(self):
        return self.names


class AvailablePosts(models.Model):
    companytype = models.ForeignKey(CompanyType, on_delete=models.CASCADE)
    names = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.companytype} - {self.names} "



class EmployerDetails(models.Model): 

  #  id = models.IntegerField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    username = models.ForeignKey('User', on_delete=models.SET_NULL, null=True, related_name='company_name')
    company_name = models.CharField(max_length = 200) 
    email = models.EmailField(blank=True)
    about_us = models.TextField()
    companytype = models.ForeignKey(CompanyType, on_delete=models.SET_NULL, null=True)
    availableposts = models.ForeignKey(AvailablePosts, on_delete=models.SET_NULL, null=True)
    strength = models.IntegerField()
    vacancies = models.IntegerField()
    last_modified = models.DateTimeField(auto_now_add = True) 
    our_requirements = models.TextField(null=True)
    our_offical_website = models.URLField(max_length=200, null=True)
    created = models.DateTimeField(default=datetime.now(), editable=False)
    updated = models.DateTimeField(default=datetime.now(), editable=False)

#    img = models.ImageField(upload_to = "images/") 
   
       
    def __str__(self): 
        return f"{self.company_name} "

    def save_model(self, request, obj, form, change):
        if getattr(obj, 'posted_by', None) is None:
            obj.posted_by = request.user.username
        obj.save()


class ApplicationData(models.Model):
    employer_name = models.CharField(max_length=255, blank=True)
  
    def __str__(self):
        return f"{self.employer_name} "


FRESHER_CHOICES = [
    ('yes', 'YES'),
    ('no', 'NO'),
   
    ]

class Application(models.Model): 

    username = models.CharField(max_length = 200, null=True) 
    first_name = models.CharField(max_length = 200, null=True) 
    last_name = models.CharField(max_length = 200, null=True) 
    email = models.EmailField(blank=True)
    company_name = models.ForeignKey(EmployerDetails,on_delete=models.SET_NULL,null=True, max_length = 200) 
    describe_yourself = models.TextField()
    resume = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(default=datetime.now(), editable=False)
    fresher = models.CharField(max_length=11,choices=FRESHER_CHOICES, null=True)
    companytype = models.ForeignKey(CompanyType, on_delete=models.SET_NULL, null=True)
   
   
    def __str__(self):
        return f"{self.company_name} "



class Ratings(models.Model):
     RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
     displayname = models.CharField(max_length = 200, null=True)    
     email = models.EmailField(blank=True)
   #  company_name = models.ForeignKey(EmployerDetails,on_delete=models.SET_NULL,null=True, max_length = 200) 
     company_name = models.CharField(max_length = 200, null=True) 
     rating = models.IntegerField(choices=RATING_CHOICES,null=True)
     review = models.TextField(null=True)
     published_at = models.DateTimeField(default=datetime.now(), editable=False)

myapp/views/employer.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, DetailView, ListView, UpdateView, TemplateView)

from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required

from ..decorators import employer_required
from ..forms import EmployerSignUpForm, EmployerForm
from ..models import User, EmployerDetails, AvailablePosts, Application, ApplicationData, Ratings

from django.http import HttpResponse
from ..utils import render_to_pdf
from django.views.generic import View
from django.db.models import Sum, Avg
# Create your views here.


class EmployerSignUpView(CreateView):
    model = User
    form_class = EmployerSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'employer'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('employer:employerhome')








@employer_required
def employerhome(request):
    context = {
        "employerdetails": EmployerDetails.objects.all(),


    }
    return render(request, "employerhome.html", context)


def specific_companypage_employer(request, company_name):
    context = {
        "details": EmployerDetails.objects.filter(company_name=company_name),
     #   "Total":list(Ratings.objects.filter(company_name=company_name).Avg(Sum('rating')).values())[0],
        "Total": Ratings.objects.filter(company_name=company_name).aggregate(rating = Avg('rating')),
        "ratings": Ratings.objects.filter(company_name=company_name),
    #specificcompanypage=Document(employer_name=employer_name)    
    #specificcompanypage.save() 
    }
    return render(request, "specific_company_pages_employer.html", context)






class EmployerFormView(CreateView):
    model = EmployerDetails
    form_class = EmployerForm
    template_name = 'employerform.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'employer'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
    #    login(self.request, user)
        return redirect('employer:employerhome')




class EmployerFormUpdateView(UpdateView):
    model = EmployerDetails
    form_class = EmployerForm
    template_name = 'employerform.html'
    success_url = reverse_lazy('employer:employerhome')

    def get_context_data(self, **kwargs):
    #    kwargs['questions'] = self.get_object().questions.annotate(answers_count=Count('answers'))
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        '''
        This method is an implicit object-level permission management
        This view will only match the ids of existing quizzes that belongs
        to the logged in user.
        '''
        return self.request.user.company_name.all()

    def get_success_url(self):
        return reverse('employer:update_form', kwargs={'pk': self.object.pk})




class EmployerFormDeleteView(DeleteView):
 
    model = EmployerDetails
    context_object_name = 'quiz'
    template_name = 'employerform_delete_confirm.html'
    success_url = reverse_lazy('employer:employerhome')

    def delete(self, request, *args, **kwargs):
        remove = self.get_object()
        messages.success(request, 'The quiz %s was deleted with success!' % remove.company_name)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.company_name.all()








@employer_required
def specificcompanypage(request, company_name):
    context = {
        "details": EmployerDetails.objects.filter(company_name=company_name),
        
    }
    return render(request, "specific_company_page.html", context)




@employer_required
def filteravailableposts(request):
    companytype_id = request.GET.get('companytype')
    filterposts = AvailablePosts.objects.filter(companytype_id=companytype_id).order_by('names')
    return render(request, 'filterby_availableposts.html', {'filterposts': filterposts})





@employer_required
class PersonListView(ListView):
    model = EmployerDetails
    context_object_name = 'people'



@employer_required
class PersonCreateView(CreateView):
    model = EmployerDetails
    #fields = ('employername', 'email', 'description', 'companytype', 'availableposts', 'employeecount', 'noofvacancy', 'last_modified')
    form_class = EmployerForm
    success_url = reverse_lazy('person_changelist')


@employer_required
class PersonUpdateView(UpdateView):
    model = EmployerDetails
    #fields = ('employername', 'email', 'description', 'companytype', 'availableposts', 'employeecount', 'noofvacancy', 'last_modified')
    form_class = EmployerForm
    success_url = reverse_lazy('person_changelist')












class ApplicationsReceivedListView(ListView):
    model = Application
    ordering = ('name', )
    context_object_name = 'company_name'
    template_name = 'filterapplications.html'

    def get_queryset(self):
        company_name = self.request.user.company_name.values_list('pk', flat=True)
     #   employer_interests = company_name.company_name.values_list('pk', flat=True)
      
        queryset = Application.objects.filter(company_name__in=company_name) 
           
        return queryset




class CompanyRatingsListView(ListView):
    model = Ratings
    ordering = ('name', )
    context_object_name = 'company_name'
    template_name = 'mycompanyratings.html'

    def get_queryset(self):
        company_name = self.request.user.company_name.values_list('pk', flat=True)
     #   employer_interests = company_name.company_name.values_list('pk', flat=True)
      
        queryset = Ratings.objects.filter(company_name__in=company_name) 
           
        return queryset





templates/apply.html
{% extends "layout.html" %}
{% block title %}
    Project3
{% endblock %} 
{% block content %}
{% load static %}

<style type="text/css">

</style>


<div class="form">	
	<div id="note">
	<h3><b>	Submit Job application<br></b></h3>
Fill up this form and send your job application.
You will receive an email notification on successfully submitting this form.</div><hr class="new1">
<form method="post" enctype="multipart/form-data">
 <table class="tab">

 	 {% csrf_token %}
  {% for field in form  %}
    {{ field.errors }}

<tr>
   <td id="td">  {{ field.label_tag }}</td><td> {{ field }} </td> <td></td>
 </tr>
  {% endfor %}
  </table><br>
 <small> Don't have a resume? <a href="{% url 'webuser:downloadtemplate'  %}"> Download our resume template</a></small><br>
  <br>
    <button id = "button" type="submit" >Send Application</button><br><br>
  </form>
{{ message }}
</div>
 

{% endblock %}

templates/download_resume_template.html
 {% load static %}   
     <link rel="stylesheet" type="text/css" href='{% static "myapp/mystyle.css" %}' />
<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
  <center><img class="image" src='{% static "myapp/icons8-user-40.png" %}'> <font color="white"><h4>Welcome, {{ user.username }}</h4><small>This is a user profile</small></font><hr class="new1"></center>
  <a href="{% url 'webuser:userhome' %}">Search companies</a>
  <a href="{% url 'webuser:infopage' %}">Company list</a>
  <a href="{% url 'webuser:sendmail' %}">Send applications</a>
  <a href="{% url 'webuser:Ratings'  %}">Leave a review</a>
  <a href="{% url 'webuser:downloadtemplate'  %}">Download our resume template</a>
  <a href="{% url 'logout'  %}">Logout</a>
</div>

<div id="main">
  <button class="openbtn" onclick="openNav()">☰ Menu</button>   
</div>
<script>
function openNav() {
  document.getElementById("mySidebar").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>

<style type="text/css">
    div.solid {border-style: solid;}
</style>



<div class="content-footer">
    <button class="button" id="btn-export" onclick="exportHTML();">Export to
        word doc</button>
</div>
<br><br>
<div id="source-html" class="solid">
<div id="title">
    <h1>(Applicant Name)</h1>
    <h3>(Designation)</h3>
    <h4>Career Objective: _________________________________________________________________________</h4>
</div><hr class="new2">


<div id="row">

    <p>
    <h4> <u>WORK EXPERIENCE</u></h4> 
    _____________________________________________________________________________________________________<br>
    _____________________________________________________________________________________________________<br>
    _____________________________________________________________________________________________________<br>
    _____________________________________________________________________________________________________<br><br><hr class="new2">

    </p><br>

    <p>
    <h4> <u>EDUCATION</u></h4> 
    <b>Masters:</b> <br>
    &nbsp &nbsp &nbspUniversity: (name)_____________________________<br>
    &nbsp &nbsp &nbspCGPA: (enter grade)___________________________<br>
    &nbsp &nbsp &nbspYear of Passing: (year)_________________________<br><br>

    <b>Graduation:</b> <br>
    &nbsp &nbsp &nbspUniversity: (name)_____________________________<br>
    &nbsp &nbsp &nbspCGPA: (enter grade)___________________________<br>
    &nbsp &nbsp &nbspYear of Passing: (year)_________________________<br><br>

    <b>High School:</b> <br>
    &nbsp &nbsp &nbspSchool: (name)_______________________________<br>
    &nbsp &nbsp &nbspGrade: (enter grade)___________________________<br>
    &nbsp &nbsp &nbspYear of Passing: (year)_________________________<br><br><hr class="new2">

    </p><br>
    <p>
    <h4> <u>PROJECTS</u></h4> 
    <b>(Project Title 1)</b> <br>
    (Description)___________________________________<br>
    ______________________________________________<br>
    ______________________________________________<br><br>

    <b>(Project Title 2)</b> <br>
    (Description)___________________________________<br>
    ______________________________________________<br>
    ______________________________________________<br><br>

    <b>(Project Title 3)</b> <br>
    (Description)___________________________________<br>
    ______________________________________________<br>
    ______________________________________________<br><br><hr class="new2">


    <p>
    <h4> <u>SKILLS</u></h4> 

    (skill 1)__________________________________   (skill 2)___________________________________<br>
    (skill 3)__________________________________   (skill 4)___________________________________<br>
    (skill 5)__________________________________   (skill 6)___________________________________<br><br><hr class="new2">
    </p><br>

    <p>
    <h4> <u>PREVIOUS ORGANIZATIONS</u></h4> 

    (details______________________________________________________________________________________________<br>
     _____________________________________________________________________________________________________<br>
    _____________________________________________________________________________________________________<br>
    _____________________________________________________________________________________________________<br>
    _____________________________________________________________________________________________________<br><br><hr class="new2">
    </p><br>

    <p>
    <h4> <u>HONOURS & AWARDS</u></h4> 

    (1)_____________________________________<br>
    (2)_____________________________________<br>
    (3)_____________________________________<br><br><hr class="new2">
    </p><br>

    <p>
    <h4> <u>PERSONAL DETAILS</u></h4> 

    (Name)____________________________________________<br>
    (Address line 1)______________________________________<br>
    (Address line 2)______________________________________<br>
    (Email)_____________________________________________<br>
    (Contact No)________________________________________<br><br><hr class="new2">

    </p>

</div>


</div>
<center><small>Resume Template by JobHunt.com</small></center>



<script>
    function exportHTML(){
       var header = "<html xmlns:o='urn:schemas-microsoft-com:office:office' "+
            "xmlns:w='urn:schemas-microsoft-com:office:word' "+
            "xmlns='http://www.w3.org/TR/REC-html40'>"+
            "<head><meta charset='utf-8'><title>Export HTML to Word Document with JavaScript</title></head><body>";
       var footer = "</body></html>";
       var sourceHTML = header+document.getElementById("source-html").innerHTML+footer;
       
       var source = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(sourceHTML);
       var fileDownload = document.createElement("a");
       document.body.appendChild(fileDownload);
       fileDownload.href = source;
       fileDownload.download = 'document.doc';
       fileDownload.click();
       document.body.removeChild(fileDownload);
    }
</script>



templates/employerdetails.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<b>Hey welcome Employer {{ user.username }}!</b>



<a href="{% url 'index' %}">home</a>

 <form method="post" id="employerForm" data-cities-url="{% url 'ajaxfilteravailableposts' %}" novalidate>


  {% csrf_token %}
  {% for field in form %}
    <p>
      {{ field.label_tag }}
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey"></small>
      {% endif %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <button type="submit">Sign up</button>
</form>



<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_companytype").change(function () {
      var url = $("#employerForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var companytypeId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'companytype': companytypeId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_availableposts").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>












</body>
</html>

templates/employerform.html
{% extends "employerlayout.html" %}
{% block title %}
    Project3
{% endblock %} 
{% block content %}
{% load static %}



<div class="form">  
 <form method="post" id="employerForm" data-cities-url="{% url 'employer:ajaxfilteravailableposts' %}" novalidate>
<div id="note">
<h3><b>Register your company with us<br></b></h3>
On publishing, these details will be visible to everyone. You can edit/delete the details you have published from the home page. <br><small>(Note: You are only allowed to edit/delete details of companies registered by you.)</small></div><hr class="new1">

  {% csrf_token %}
  <table class="tab">
  {% for field in form %}
    <p>
  <tr>
   <td id="td">    {{ field.label_tag }}
     </td><td>  {{ field }}</td> <td></td>
 </tr> 
      {% if field.help_text %}
        <small style="color: grey"></small>
      {% endif %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}</table>
  <br>
  <button id="button" type="submit">Register Company</button>
   <button onclick="myFunction()" id="button" type="submit">Update Details</button>
</form>
<br>
<br>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_companytype").change(function () {
      var url = $("#employerForm").attr("data-cities-url");  
      var companytypeId = $(this).val();  // get the selected companytypeId from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                   
        data: {
          'companytype': companytypeId       
        },
        success: function (data) {   
          $("#id_availableposts").html(data);  
        }
      });

    });
  </script>

<script>
function myFunction() {
  alert("Update Sucessfull! Navigate to home page to view changes");
}
</script>




</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html style="height:100%">
<head>
    <meta charset="UTF-8">    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

 {% load static %}   
     <link rel="stylesheet" type="text/css" href='{% static "myapp/mystyle.css" %}' />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"> 
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>    
       <!-- BOOTSTRAP CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

        <!-- BOOTSTRAP JS (Last) -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>       

</head>
        {% block head %}
        {% endblock %}        
        <title>
          CS Final Project: {% block title %}{% endblock %}
        </title>
    </head>
<style>


</style>



<body class="body">

<div id="columntwo">    
 <div id="header">
  JobHunt
 </div> 
</div>


<div id="footer">
  <p>Developed by Meenu Gigi</p>
</div> 



<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
  <center><img class="image" src='{% static "myapp/icons8-user-40.png" %}'> <font color="white"><h4>Welcome, {{ user.username }}</h4><small>This is a user profile</small></font><hr class="new1"></center>
 <a href="{% url 'webuser:userhome' %}">Search companies</a>
  <a href="{% url 'webuser:infopage' %}">Company list</a>
  <a href="{% url 'webuser:sendmail' %}">Send applications</a>
  <a href="{% url 'webuser:Ratings'  %}">Leave a review</a>
  <a href="{% url 'webuser:downloadtemplate'  %}">Download our resume template</a>
  <a href="{% url 'logout'  %}">Logout</a>
</div>

<div id="main">
  <button class="openbtn" onclick="openNav()">☰</button>  
 
</div>

<script>
function openNav() {
  document.getElementById("mySidebar").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>
   


        {% block content %}
        {% endblock %}

</body>
 
</html>

templates/userhome.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>

   {% load static %}   
     <link rel="stylesheet" type="text/css" href='{% static "myapp/mystyle.css" %}' />
     
<style>
.body{
   background-color: #001a33;
}

.openbtn {
  font-size: 20px;
  cursor: pointer;
 background-color:  #e6e6e6;
  color: #00264d;
  padding: 10px 15px;
  border: none;
}

</style>

<body class="body">

<div id="top">




<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
  <center><img class="image" src='{% static "myapp/icons8-user-40.png" %}'> <font color="white"><h3>Welcome, {{ user.username }}</h3><small>This is a user profile</small></font><hr class="new1"></center>
  <a href="{% url 'webuser:userhome' %}">Search companies</a>
  <a href="{% url 'webuser:infopage' %}">Company list</a>
  <a href="{% url 'webuser:sendmail' %}">Send applications</a>
  <a href="{% url 'webuser:Ratings'  %}">Leave a review</a>
  <a href="{% url 'webuser:downloadtemplate'  %}">Download our resume template</a>
  <a href="{% url 'logout'  %}">Logout</a>
</div>

<div id="main">
  <button class="openbtn" onclick="openNav()">☰ Menu</button>   
</div>
<script>
function openNav() {
  document.getElementById("mySidebar").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>




<div id="head">
JobHunt
</div>



<div id="search">
<form action="{% url 'webuser:searchposts' %}" method="GET" value="{{request.GET.q}}">
<input id="textsearch" type="text" name="q" value="{{request.GET.q}}" placeholder="Search by company name"/>
<input id="button" type="submit" name="submit" value="Search" />
</form>
</div>

{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}
<div id="searchresults">
<h1>Results for <b>{{ request.GET.q }}</b></h1>
<br/><br/>

</div>

{% for result in results %}
<div id="result">
<a href="{% url 'webuser:specificcompanypage' result.company_name %}">{{result.company_name}}</a>
<br/>

{{result.email}}
</div>
<br/><hr>

{% endfor %}
{% else %}
<div id="result">
No search results for this query
</div>
{% endif %}
{% endif %}


</div>


<div class="row">
	<div class="mid">
  <div class="column">
    <div class="card">
    	<img class="image" src='{% static "myapp/job.png" %}'>
      <h3>We have millions of jobs for you.</h3>
      <p>Discover jobs</p>
     <p>Rate a company</p>
    </div>
  </div>
 <div class="column">
    <div class="card">
    	<img class="image" src='{% static "myapp/resume.png" %}'>
      <h3>Don't have a resume?</h3>
      <p>We provide resume templates</p>
     <p>Download for free!</p>
    </div>
  </div>
  <div class="column">
    <div class="card">
    	<img class="image" src='{% static "myapp/hire.png" %}'>
      <h3>Are you hiring?</h3>
      <p>Post jobs for free</p>
     <p>Receive applications</p>
    </div>
  </div>
  
 
  
 </div> 
</div>


</body>
</html>